sudo: required
services:
  - docker

before_install:
  - docker build -t kjtsai/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kjtsai/react-test npm test -- --coverage

after_success:
  - docker build -t kjtsai/multi-client ./client
  - docker build -t kjtsai/multi-nginx ./nginx
  - docker build -t kjtsai/multi-server ./server
  - docker build -t kjtsai/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push kjtsai/multi-client
  - docker push kjtsai/multi-nginx
  - docker push kjtsai/multi-server
  - docker push kjtsai/multi-worker
